### ISSUE TITLE
Unable to build on Windows 7x64

### ISSUE THREAD

**Issue by TimNZ** [c4milo/node-webkit-agent#46]
Node 0.10.20
Linker error regarding symbols already defined in profile.obj

c:\Development\Projects\HostedPortal\Source\WebApp\server\node_modules\webkit-devtools-agent>node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-b
in\....\node_modules\node-gyp\bin\node-gyp.js" rebuild
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  profiler.cc
  profile.cc
  snapshot.cc
  profile_node.cc
  heap_profiler.cc
  cpu_profiler.cc
C:\Users\tshnaider.node-gyp\0.10.20\deps\v8\include\v8.h(179): warning C4506: no definition for inline function 'v8::Persistent<T> v8::Persistent<T>::New(v8::
Handle<T>)' [c:\Development\Projects\HostedPortal\Source\WebApp\server\node_modules\webkit-devtools-agent\build\profiler.vcxproj]
          with
          [
              T=v8::Object
          ]
C:\Users\tshnaider.node-gyp\0.10.20\deps\v8\include\v8.h(184): warning C4506: no definition for inline function 'v8::Persistent<T> v8::Persistent<T>::New(v8::
Handle<T>)' [c:\Development\Projects\HostedPortal\Source\WebApp\server\node_modules\webkit-devtools-agent\build\profiler.vcxproj]
          with
          [
              T=v8::Object
          ]
C:\Users\tshnaider.node-gyp\0.10.20\deps\v8\include\v8.h(184): warning C4506: no definition for inline function 'v8::Persistent<T> v8::Persistent<T>::New(v8::
Handle<T>)' [c:\Development\Projects\HostedPortal\Source\WebApp\server\node_modules\webkit-devtools-agent\build\profiler.vcxproj]
          with
          [
              T=v8::Object
          ]
C:\Users\tshnaider.node-gyp\0.10.20\deps\v8\include\v8.h(184): warning C4506: no definition for inline function 'v8::Persistent<T> v8::Persistent<T>::New(v8::
Handle<T>)' [c:\Development\Projects\HostedPortal\Source\WebApp\server\node_modules\webkit-devtools-agent\build\profiler.vcxproj]
          with
          [
              T=v8::Object
          ]
node.lib(node.exe) : error LNK2005: "public: __thiscall v8::Handle<class v8::Object>::Handle<class v8::Object>(class v8::Object *)" (??0?$Handle@VObject@v8@@@v
8@@QAE@PAVObject@1@@Z) already defined in profile.obj [c:\Development\Projects\HostedPortal\Source\WebApp\server\node_modules\webkit-devtools-agent\build\profi
ler.vcxproj]
node.lib(node.exe) : error LNK2005: "public: __thiscall v8::Handle<class v8::FunctionTemplate>::Handle<class v8::FunctionTemplate>(void)" (??0?$Handle@VFunctio
nTemplate@v8@@@v8@@QAE@XZ) already defined in profile.obj [c:\Development\Projects\HostedPortal\Source\WebApp\server\node_modules\webkit-devtools-agent\build\p
rofiler.vcxproj]
     Creating library c:\Development\Projects\HostedPortal\Source\WebApp\server\node_modules\webkit-devtools-agent\build\Release\profiler.lib and object c:\Dev
  elopment\Projects\HostedPortal\Source\WebApp\server\node_modules\webkit-devtools-agent\build\Release\profiler.exp
c:\Development\Projects\HostedPortal\Source\WebApp\server\node_modules\webkit-devtools-agent\build\Release\profiler.node : fatal error LNK1169: one or more mul
tiply defined symbols found [c:\Development\Projects\HostedPortal\Source\WebApp\server\node_modules\webkit-devtools-agent\build\profiler.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd c:\Development\Projects\HostedPortal\Source\WebApp\server\node_modules\webkit-devtools-agent
gyp ERR! node -v v0.10.20
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok
npm ERR! weird error 1
npm ERR! not ok code 0

**Comment by jon49** [comment]
Not sure if this is the same issue or not, but it looks similar:

> webkit-devtools-agent@0.3.1 install C:\Users\1198462\Source\Repos\mobiledlr\mobiledlr\node_modules\webkit-devtools
-agent
> node-gyp rebuild


C:\Users\1198462\Source\Repos\mobiledlr\mobiledlr\node_modules\webkit-devtools-agent>node "C:\Program Files (x86)\no
dejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild 
child_process: customFds option is deprecated, use stdio instead.
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  cpu_profiler.cc
  heap_profiler.cc
  profile.cc
  profile_node.cc

........................................................................

C:\Users\1198462\.node-gyp\0.12.0\deps\v8\include\v8.h(816) : see declaration of 'v8::HandleScope::HandleS
cope'
          C:\Users\1198462\.node-gyp\0.12.0\deps\v8\include\v8.h(800) : see declaration of 'v8::HandleScope'
..\src\snapshot.cc(127): error C2039: 'handle_' : is not a member of 'v8::Object' [C:\Users\1198462\Source\Repos\mob
iledlr\mobiledlr\node_modules\webkit-devtools-agent\build\profiler.vcxproj]
          C:\Users\1198462\.node-gyp\0.12.0\deps\v8\include\v8.h(2110) : see declaration of 'v8::Object'
..\src\snapshot.cc(128): error C2660: 'v8::Integer::New' : function does not take 1 arguments [C:\Users\1198462\Sour
ce\Repos\mobiledlr\mobiledlr\node_modules\webkit-devtools-agent\build\profiler.vcxproj]
..\src\snapshot.cc(129): fatal error C1903: unable to recover from previous error(s); stopping compilation [C:\Users
\1198462\Source\Repos\mobiledlr\mobiledlr\node_modules\webkit-devtools-agent\build\profiler.vcxproj]
gyp
 
ERR!
 
build error
 
gyp
 
ERR!
 
stack
 Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp
 
ERR!
 
stack
     at ChildProcess.onExit (C:\Program Files 
(x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp
 
ERR!
 
stack
     at ChildProcess.emit (events.js:110:17)
gyp
 
ERR!
 
stack
     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp
 
ERR!
 
System
 Windows_NT 6.1.7601
gyp
 
ERR!
 
command
 "node" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp
 ERR! cwd C:\Users\1198462\Source\Repos\mobiledlr\mobiledlr\node_modules\webkit-devtools-agent
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm
 
ERR!
 Windows_NT 6.1.7601
npm
 
ERR!
 
argv
 "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files 
(x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "webkit-devtools-agent" "--save"
npm
 
ERR!
 
node
 v0.12.0
npm
 
ERR!
 
npm 
 v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! webkit-devtools-agent@0.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the webkit-devtools-agent@0.3.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the webkit-devtools-agent package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls webkit-devtools-agent
npm ERR! There is likely additional logging output above.
npm
 
ERR!
 Please include the following file with any support request:
npm
 
ERR!
     C:\Users\1198462\Source\Repos\mobiledlr\mobiledlr\npm-debug.log

**Comment by jon49** [comment]
After some more investigation it appears that it was because I was trying to use node 0.12.0. Apparently there have been so many API changes that many projects haven't kept up. Back to 0.10 for me!
